# most personal metadata can be found in ./resume.json

- description: Pomosh App
  img: ../src/images/tomato.png
  productImg: ../src/images/tomato.png
  downloadBadgeDark: ../src/images/downloadBadgeDarg.svg
  repo: https://github.com/stevenselcuk/pomosh
  bugs: https://github.com/stevenselcuk/pomosh/issues
  gatsbyThemePromotion: https://github.com/stevenselcuk/pomosh-website

  availability:
    status: false
    available: 'Download on App Store'
    unavailable: Not available for download.
